### PR TITLE
db for customer

### PR DESCRIPTION
**Pull request by ZacharyCline**
# Description
Add a table to db for customer. Created tests for saving a customer and registering a customer to the db.

## Testing

[x] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[x] I certify that all existing tests pass

## Documentation
There is not new documentation in this pull request that must be reviewed..

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout <feature_branch>
```
Testing:
After checking out the branch testing should create a db file. You can now go see the database and checkout bob bobbins data.

### CODE REVIEW

**Comment by Dmart331** [comment]
🚀

**Comment by abbyfleming** [comment]
Can you give testing instructions? What should we see? Thank youuuu!

**Comment by ZacharyCline** [comment]
Should have a little more information on what you will see there.

**Comment by abbyfleming** [comment]
Looks great! Let's get some clarification about where the db files goes before final merge.

**Comment by ZacharyCline** [comment]
hold up team... i broke everything!!!! 👎

**Comment by ZacharyCline** [comment]
ok fixed it agian.. just deleted the code that broke everything... Currently this pull request is capable of adding customers to a db.

**Comment by Dmart331** [comment]
🚀

**Comment by Dmart331** [comment]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Comment by peterStaggs** [comment]
🚀

**Pull request merged**
