### PR TITLE
Create Order / CustomerId

### PR DESCRIPTION
**Pull request by abbyfleming**
# Description
Started the process for grabbing the customerID for Suzy. For the Order table: a unique key, customerId, paymentId, and complete is needed.

## Testing

[X] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[X] I certify that all existing tests pass

## Documentation
Comments have been added for clarity.

[X] There is new documentation in this pull request that must be reviewed..

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout amOrderDB
```

## Steps to Test
Outline the steps to test the code in this pull request.

1. Run testOrder.py
2. Check Order.py
3. Check Customer.py

### CODE REVIEW

**Comment by Dmart331** [comment]
🚀

**Comment by Dmart331** [comment]
🚀  👨

**Comment by ZacharyCline** [comment]
All good after knocking out some small changes we mentioned! Nice work! Tests look awesome! 🚀

**Comment by shawn-mit** [comment]
:rocket:  !!!!!!!

**Comment by peterStaggs** [comment]
🚀

**Pull request merged**
